### ISSUE TITLE
Freebsd build

### ISSUE THREAD

**Issue by ola-mattsson** [jmccl/acme-lw#7]
Hi, can't build on freebsd.

* libcurl is found with `find_packaged(CURL REQUIRED)` but the resulting target CURL::libcurl is not used.
* `#include <ctime>` missing in `acme-lw.h`
* Checking for existence `<filesystem>` to avoid deprecation warning on `<experimental/filesystem>` when found.
* Suggested slight change in cmake build instructions.

Tried to open a PR, didn't get permission with token so here is a little patch
[freebsd_patch.tar.gz](https://github.com/jmccl/acme-lw/files/7654203/freebsd_patch.tar.gz)

**Comment by jmccl** [comment]
Thanks for the bug and patch.

I checked in some changes that address the curl and filesystem issues and and still work with older debian (stretch) releases. This now builds for me in a FreeBSD 13.0 vm. I didn't seem to need the ctime include.

I didn't pick up the cmake build suggestion as I'd prefer to keep the readme as simple as possible. People who prefer to do an 'out of source' build know how to do that, I assume.

Can you test to see if this works for you? My main concerns are the ctime issue and whether that (or anything else) was somehow due to an older version of FreeBSD or possibly some other config issue.

**Comment by ola-mattsson** [comment]
Hi, Quick response! thanks.

I'm on freebsd 12.2, since that's the newest Digital Ocean provide. clang 10.
Still needs the <ctime> header.

I Agree, it's probably time to stop searching for `<experimental/filesystem>` assuming it is there if `<filesystem>` is not found.

**Comment by jmccl** [comment]
Huh. Weird.

I've added the header. Let me know if you've got any issues.

**Comment by ola-mattsson** [comment]
No issue, builds fine now thanks!
